### ISSUE TITLE
Add Impressum & Links in Footer

### ISSUE THREAD

**Issue by bnjmnsbl** [technologiestiftung/citylab-hackthecrisis#25]
Link to citylab-berlin.org from CityLAB Logo 

Link to Impressum: https://www.citylab-berlin.org/legalnote

**Comment by bnjmnsbl** [comment]
please also add Logo of Technologiestiftung: https://www.citylab-berlin.org/tsb.svg

**Comment by fabianmoronzirfas** [comment]
> please also add Logo of Technologiestiftung: citylab-berlin.org/tsb.svg

Was already there
